from __future__ import annotations

from pathlib import Path

from drupal_ai_module_generator.mcp_client import MCPClient
from drupal_ai_module_generator.models import ModulePlan
from drupal_ai_module_generator.templates import (
    controller_php,
    info_yml,
    module_file,
    routing_yml,
    service_php,
    services_yml,
)


class ModuleGenerator:
    def __init__(self, client: MCPClient) -> None:
        self.client = client

    def generate(self, plan: ModulePlan) -> None:
        machine = plan.machine_name
        self.client.write_file(f"{machine}/{machine}.info.yml", info_yml(plan))
        self.client.write_file(f"{machine}/{machine}.module", module_file(plan))
        self.client.write_file(f"{machine}/README.md", self._readme(plan))

        if plan.services:
            self.client.write_file(f"{machine}/{machine}.services.yml", services_yml(plan))
            for service in plan.services:
                rel_path = self._class_path(service.class_name)
                content = service_php(service.class_name, service.description)
                self.client.write_file(f"{machine}/{rel_path}", content)

        if plan.routes:
            self.client.write_file(f"{machine}/{machine}.routing.yml", routing_yml(plan))
            for route in plan.routes:
                class_path = self._class_path(route.controller)
                method = route.controller.split("::")[-1] if "::" in route.controller else "index"
                class_name = route.controller.split("::")[0]
                self.client.write_file(
                    f"{machine}/{class_path}",
                    controller_php(class_name, method),
                )

    def _readme(self, plan: ModulePlan) -> str:
        return (
            f"# {plan.name}\n\n"
            f"{plan.description}\n\n"
            "## Generated by\n\n"
            "DeepSeek R1 + MCP module generator.\n"
        )

    @staticmethod
    def _class_path(class_name: str) -> str:
        class_name = class_name.split("::")[0]
        if not class_name.startswith("Drupal\\"):
            raise ValueError("Class names must start with Drupal\\")
        parts = class_name.split("\\")
        if len(parts) < 3:
            raise ValueError("Class name must include module namespace")
        return str(Path("src", *parts[2:]).with_suffix(".php"))
